apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancer-deployment
  labels:
    app: balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balancer
  template:
    metadata:
      labels:
        app: balancer
    spec:
      containers:
        - name: balancer
          image: tequilac/balancer:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/balancer/res/config"
              name: balancer-cf
      volumes:
        - name: balancer-volume
          configMap:
            name: balancer-cf

---
apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app.kubernetes.io/name: balancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: balancer-cf
data:
  conf.yaml: |
    ---
    streams:
    - frame_rate_timeout: 1
      rtsp_url: url
      frame_strategy: DROP
      mqtt_info:
        client_id: id-1000
        username: admin
        password: admin
        broker: broker
        port: 6000
        topic: yolo
